import ingredients from 'constants/ingredients'

const { ananas, tomaatti, jalapenos, oliivi, paprika } = ingredients

export default [
	{ name: tomaatti, price: 6 },
	{ name: 'bearnaisesauce', price: 6 },
	{ name: 'hvidløg', price: 6 },
	{ name: 'salatmayonnaise', price: 6 },
	{ name: 'champignon', price: 14 },
	{ name: oliivi, price: 14 },
	{ name: 'cocktailpølser', price: 19 },
	{ name: 'kødsauce', price: 19 },
	{ name: 'ost', price: 19 },
	{ name: 'rejer', price: 19 },
	{ name: 'chili', price: 6 },
	{ name: 'ketchup', price: 6 },
	{ name: ananas, price: 14 },
	{ name: jalapenos, price: 14 },
	{ name: paprika, price: 14 },
	{ name: 'gorgonzola', price: 19 },
	{ name: 'kebab', price: 19 },
	{ name: 'pepperoni', price: 19 },
	{ name: 'skinke', price: 19 },
	{ name: 'dressing i bæger', price: 6 },
	{ name: 'remoulade', price: 6 },
	{ name: 'æg', price: 14 },
	{ name: 'løg', price: 14 },
	{ name: 'bacon', price: 19 },
	{ name: 'Hakket Oksekød', price: 19 },
	{ name: 'kylling', price: 19 },
	{ name: 'pizzadej', price: 19 },
	{ name: 'tunfisk', price: 19 },
]

// export default {
// 	tomaatti: { name: tomaatti, price: 6 },
// 	bearnaisesauce: { name: 'bearnaisesauce', price: 6 },
// 	hvidlog: { name: 'hvidløg', price: 6 },
// 	salatmayonnaise: { name: 'salatmayonnaise', price: 6 },
// 	champignon: { name: 'champignon', price: 14 },
// 	oliivi: { name: oliivi, price: 14 },
// 	cocktailpolser: { name: 'cocktailpølser', price: 19 },
// 	kodsauce: { name: 'kødsauce', price: 19 },
// 	ost: { name: 'ost', price: 19 },
// 	rejer: { name: 'rejer', price: 19 },
// 	chili: { name: 'chili', price: 6 },
// 	ketchup: { name: 'ketchup', price: 6 },
// 	ananas: { name: ananas, price: 14 },
// 	jalapenos: { name: jalapenos, price: 14 },
// 	paprika: { name: paprika, price: 14 },
// 	gorgonzola: { name: 'gorgonzola', price: 19 },
// 	kebab: { name: 'kebab', price: 19 },
// 	pepperoni: { name: 'pepperoni', price: 19 },
// 	skinke: { name: 'skinke', price: 19 },
// 	dressing: { name: 'dressing i bæger', price: 6 },
// 	remoulade: { name: 'remoulade', price: 6 },
// 	egg: { name: 'æg', price: 14 },
// 	log: { name: 'løg', price: 14 },
// 	bacon: { name: 'bacon', price: 19 },
// 	hakketOksekod: { name: 'Hakket Oksekød', price: 19 },
// 	kylling: { name: 'kylling', price: 19 },
// 	pizzadej: { name: 'pizzadej', price: 19 },
// 	tunfisk: { name: 'tunfisk', price: 19 },
// }
