export default {
	kinkku: 'kinkku',
	ananas: 'ananas',
	salami: 'salami',
	sipuli: 'sipuli',
	valkosipuli: 'valkosipuli',
	tonnikala: 'tonnikala',
	aurajuusto: 'aurajuusto',
	katkarapu: 'katkarapu',
	pinaatti: 'pinaatti',
	kananmuna: 'kananmuna',
	mozzarella: 'mozzarella',
	tomaatti: 'tomaatti',
	parmesanijuusto: 'parmesanijuusto',
	parsa: 'parsa',
	cheddarjuusto: 'cheddarjuusto',
	herkkusieni: 'herkkusieni',
	rucola: 'rucola',
	jalopeno: 'jalopeno',
	oliivi: 'oliivi',
	maissi: 'maissi',
	paprika: 'paprika',
	majoneesi: 'majoneesi',
	turkinpippuri: 'turkinpippuri',
	salaatti: 'salaatti',
	bbqKastike: 'BBQ-kastike',
	piatti: 'piåtti',
}
