export default {
	kinkku: 'kinkku',
	ananas: 'ananas',
	salami: 'salami',
	log: 'løg',
	valkolog: 'valkolog',
	tonnikala: 'tonnikala',
	aurajuusto: 'aurajuusto',
	katkarapu: 'katkarapu',
	pinaatti: 'pinaatti',
	kananmuna: 'kananmuna',
	mozzarella: 'mozzarella',
	tomat: 'tomat',
	parmesanijuusto: 'parmesanijuusto',
	parsa: 'parsa',
	cheddarjuusto: 'cheddarjuusto',
	herkkusieni: 'herkkusieni',
	rucola: 'rucola',
	jalapenos: 'jalapenos',
	oliven: 'oliven',
	maissi: 'maissi',
	paprika: 'paprika',
	mayonnaise: 'mayonnaise',
	chili: 'chili',
	salat: 'salat',
	bbqKastike: 'BBQ-kastike',
	piatti: 'piåtti',
}
